'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TB_Contact
    Public Property ContactID As Integer
    Public Property Name As String
    Public Property Surname As String
    Public Property Surname2 As String
    Public Property Telephone As String
    Public Property e_mail As String

End Class
